### ISSUE TITLE
I don't know the scene to use it

### ISSUE THREAD

**Issue by jinguoliang** [JakeWharton/OverloadReturn#1]
Hello， I know it what it do, but don't know the scene where to use it.
I think out a scene but it can use generic
``` java
    @Override
    public <T extends View> T findViewById(@IdRes int id) {
        return getDelegate().findViewById(id);
    }
```

**Comment by mhewedy** [comment]
> This is useful for migrating a public API without breaking binary compatibility with old clients.

**Comment by JakeWharton** [comment]
The library's extremely niche use case is described in the README (which admittedly isn't complete yet). I'm not sure what question you're specifically asking or what relevance that code snippet has.

**Comment by WOLVIE97** [comment]
Wowwwww....😜💯
